name: tambak_iot
description: "Aplikasi Monitoring Kualitas Air Tambak IoT"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^7.2.2
  fl_chart: ^0.69.2
  flutter_local_notifications: ^18.0.1
  mqtt_client: ^10.5.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# HANYA ADA SATU KUNCI 'flutter:' di sini
flutter:
  uses-material-design: true

  assets:
    - assets/alarm_tet.wav
    - assets/logo.png